name: CI/CD for Strapi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust Node.js version as per your requirements

      - name: Fix dpkg interrupted error
        run: sudo dpkg --configure -a

      - name: Update and upgrade system packages
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Install Node.js and npm
        run: |
          sudo apt install -y nodejs npm

      - name: Upgrade npm
        run: sudo npm install -g npm@8  # Install npm version 8 which supports Node.js 14

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            # Check if the 'strapi-test' directory exists and is not empty, and remove it if necessary
            if [ -d "strapi-test" ]; then
              rm -rf strapi-test
            fi

            # Clone the Strapi repository
            git clone https://github.com/ashitha99/strapi-test.git
            cd strapi-test

            # Start the Strapi application with PM2
            pm2 start npm --name "strapi" -- start  # Use 'start' instead of 'develop' for production

            # Optionally, you can restart instead of start if it's already running
            # pm2 restart strapi || pm2 start npm --name "strapi" -- start
