name: CI/CD for Strapi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Upgrade npm
      run: |
        npm install -g npm@latest
        npm --version

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e

          echo "Configuring dpkg if interrupted..."
          sudo dpkg --configure -a

          echo "Updating package list and upgrading packages..."
          sudo apt update
          sudo apt upgrade -y

          echo "Installing Node.js and npm if not already installed..."
          sudo apt install -y nodejs npm

          echo "Checking Node.js version..."
          node --version

          echo "Checking npm version..."
          npm --version

          echo "Checking if 'strapi-test' directory exists and removing it if necessary..."
          if [ -d "strapi-test" ]; then
            rm -rf strapi-test
          fi

          echo "Cloning the Strapi repository..."
          git clone https://github.com/ashitha99/strapi-test.git
          cd strapi-test

          echo "Installing project dependencies..."
          npm install

          echo "Starting the Strapi application using pm2..."
          pm2 start npm --name "strapi" -- start

          echo "Deployment complete."
